### ISSUE TITLE
AWS provider not ignoring changes to profile/AWS_PROFILE

### ISSUE THREAD

**Issue by pierlucg-xs** [pulumi/pulumi-aws#1470]
We're using multiple AWS accounts and need to interact with them within Pulumi. In my stack config I have:

```yaml
config:
  aws:allowedAccountIds:
    - '12345'
  aws:assumeRole:
    roleArn: arn:aws:iam::12345:role/some-role
    sessionName: pulumi
  aws:region: us-east-1
```

and in my code I have:

```ts
const rootAccountProvider = new aws.Provider(
  'rootAccount',
  {
    allowedAccountIds: ['9876'],
    assumeRole: {
      roleArn: 'arn:aws:iam::9876:role/some-other-role',
      sessionName: 'pulumi',
    },
  },
  {ignoreChanges: ['profile']}, // this doesn't help)
);
```

## Expected behavior
I expect no change to occur based on the user's `AWS_PROFILE` value

## Current behavior
My `AWS_PROFILE` is set to `mfa` and when I run a `preview` or an `up`, I get:

```txt
Do you want to perform this update? details
  pulumi:pulumi:Stack: (same)
    [urn=urn:...]
    ~ pulumi:providers:aws: (update)
        [id=...]
        [urn=urn:...]
      + profile                  : "mfa"     <- no pls
```

## Context (Environment)

using S3 backend
pulumi version v3.1.0

------
Slack discussion: https://pulumi-community.slack.com/archives/C84L4E3N1/p1619636116119700
