### ISSUE TITLE
pulumi import missing properties

### ISSUE THREAD

**Issue by felskrone** [pulumi/pulumi-aws#1894]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details
Im trying to import/reuse existing CloudFormation templates in pulumi. The resources (IAMUsers and S3 buckets) already exist on AWS and i want to port them to pulumi.

The existing IAMUser template has 3 properties and 1 tag and look like this:

```
...
Parameters:
  UserName:
    Type: String
    Description: A name for the IAM user.
  VariablesJSON:
    Type: String
    Description: A stringified...
    Default: '{"S3BucketName":"s3name"}'
  PolicyName:
    Type: String
    Description: A policy name.
  DMZTag:
    Type: String
    Description: (Optional) Description...
    Default: "NONE"
    AllowedValues:
...
```
All properties are verified to be set on existing IAMUsers in AWS which im trying to import.

When importing the existing IAMUser using pulumi
```
$ pulumi import aws:iam/user:User user-storage-ro user-storage-ro
```

this is all the code generated

```python
user_storage_ro = aws.iam.User(
"user-storage-ro",
name="user-storage-ro",
opts=pulumi.ResourceOptions(protect=True))
```
### Steps to reproduce

1. Create an IAMUser in AWS
2. Give it the following inline policy for an S3 bucket
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:Get*",
                "s3:List*"
            ],
            "Resource": [
                "arn:aws:s3:::<bucketname>",
                "arn:aws:s3:::<bucketname>/*"
            ]
        }
    ]
}
```
and try importing it into pulumi.
