### ISSUE TITLE
Error message missing information while parsing config

### ISSUE THREAD

**Issue by hsundell** [pulumi/pulumi-aws#2184]
### What happened?

Error message that gets produced (even on `-d -v10`) just tells that there exist an invalid key, but gives no suggestion what the invalid key is or what line it might be on.

```bash
error: could not validate provider configuration: 1 error occurred:
  	* Invalid or unknown key
...
error Command failed with exit code 255.
```

### Steps to reproduce

Finally tracked it down by removing half the config at a time and managed to narrow it down to a single key after much trial & error.

Culprit was, probably old, config value under `aws:endpoints` that I need in my localstack setup `mobileanalytics: http://localhost:4566`. This value has probably existed and has been valid in the past, but now it causes an error. The problem is not the key itself, but the unhelpful nature of the error message.

Can be reproduced by adding e.g.
```yaml
config:
  aws:endpoints:
    - accessanalyzer: http://localhost:4566
      account: http://localhost:4566
      acm: http://localhost:4566
      acmpca: http://localhost:4566
      alexaforbusiness: http://localhost:4566
      amp: http://localhost:4566
      amplify: http://localhost:4566
      amplifybackend: http://localhost:4566
      apigateway: http://localhost:4566
      apigatewayv2: http://localhost:4566
      appautoscaling: http://localhost:4566
      appconfig: http://localhost:4566
      appflow: http://localhost:4566
      appintegrations: http://localhost:4566
      appintegrationsservice: http://localhost:4566
      applicationautoscaling: http://localhost:4566
      applicationcostprofiler: http://localhost:4566
      applicationdiscovery: http://localhost:4566
      applicationdiscoveryservice: http://localhost:4566
      applicationinsights: http://localhost:4566
      appmesh: http://localhost:4566
      appregistry: http://localhost:4566
      apprunner: http://localhost:4566
      appstream: http://localhost:4566
      appsync: http://localhost:4566
      athena: http://localhost:4566
      auditmanager: http://localhost:4566
      augmentedairuntime: http://localhost:4566
      autoscaling: http://localhost:4566
      mobileanalytics: http://localhost:4566
```

### Expected Behavior

Would expect the error message to contain the key or at least the line in the file that the invalid key was found on.

### Actual Behavior

Not that

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
