### ISSUE TITLE
Releasing an alpha version does not tag the SDK

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-aws#2704]
### What happened?

Following a bot-initiated alpha release:

```
@release-bot release pulumi-aws v6.0.2-alpha.1
```

Observing that `sdk/v6.0.2-alpha.1` tag has not been added to the repository.  Therefore the Go SDK is not released.

The job had a Java publishing failure but that seems like it should be unrelated.

### Expected Behavior

Releasing an alpha releases the Go SDK.

### Steps to reproduce

N/A

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mnlumi** [comment]
@t0yv0 what else needs to happen here going forward?

**Comment by t0yv0** [comment]
After the repo transitions to ci-mgmt workflows we can move it to ci-mgmt; something is not quite reliable with the workflow generation. Looks like sdk/v6.0.2 got created so maybe there's something like Java publishing failure impeding the Go publishing failure.

**Comment by t0yv0** [comment]
So in fact

release.yml include this:

```
  tag_sdk:
    name: tag_sdk
    needs: publish_sdk
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Install pulumictl
      uses: jaxxstorm/action-install-gh-release@v1.5.0
      with:
        repo: pulumi/pulumictl
    - name: Add SDK version tag
      run: git tag sdk/v$(pulumictl get version --language generic) && git push origin
        sdk/v$(pulumictl get version --language generic)
```

But it does not apply to alpha pre-releases, so that's probably what's wrong here. We should fix it so we can tag alpha releases seamlessly.
