### ISSUE TITLE
Pre-release versions include a hash

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-aws#2721]
Due to some interesting behavior of pulumictl and/or the build configurations, I cannot do this:

```
  provider:
    type: pulumi:providers:aws
    options:
      version: 6.0.2-alpha.2
```

And instead need to do this:

```
  provider:
    type: pulumi:providers:aws
    options:
      version: 6.0.2-alpha.2+9b14ba69
```

When using pre-releases in YAML. Other languages might be affected also.
