### ISSUE TITLE
Secret tags inherited from the default provider leak into the state

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-aws#2820]
### What happened?

Continued from https://github.com/pulumi/pulumi-aws/pull/2791 noticing that if a default provider has secret tags, and they're added to a given resource's tags, the secret bit is lost and the secret leaks into the statefile.

```yaml
name: test-aws-defaultprovleak
runtime: yaml
resources:

  prov:
    type: pulumi:providers:aws
    properties:
      defaultTags:
        that:
          fn::secret: mysecret 

  res:
    type: aws:s3:BucketV2
    options:
      provider: ${prov}
```

```pulumi up``` this and observe "mysecret" in the state.

### Example

See above.

### Output of `pulumi about`

N/A

### Additional context

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
