### ISSUE TITLE
Suddenly getting AWS provider validation on my SDK when I didn't have it before

### ISSUE THREAD

**Issue by zbuchheit** [pulumi/pulumi-aws#3360]
### What happened?

Upon upgrading versions of pulumi/pulumi and pulumi/aws I am now getting provider validation errors. 

### Example

Previously I was using arbitrary keys in my aws namespace without issue. For example, `aws:foo: value` was allowed to be used, but upon version upgrades I am now getting the follow error `pulumi:providers:aws resource 'default_6_13_0' has a problem: could not validate provider configuration: Invalid or unknown key. Check pulumi config get aws:foo.`

### Output of `pulumi about`

TODO

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by zbuchheit** [comment]
it appears this happened as a result of having a default provider. If I disable the aws provider, and explicitly pass it into my resources it no longer performs validation on my Pulumi.dev.yaml file and I can use arbitrary keys

**Comment by iwahbe** [comment]
I believe that this is intended behavior. We have produced this error when using a default provider for all released versions of pulumi-aws v6. Only default providers read `config:`, so you wouldn't get this error if no default provider is used.


---

#### Testing

I tested AWS's behavior with this program:

```yaml
name: dev-yaml
runtime: yaml
config:
  aws:foo: bar
  aws:region: us-west-2

resources:
  bucket:
    type: aws:s3:Bucket
    options:
      version: v6.1.0
```

I see the same error for all pulumi-aws v6 versions:

```
  pulumi:providers:aws (default_6_1_0):
    error: pulumi:providers:aws resource 'default_6_1_0' has a problem: could not validate provider configuration: Invalid or unknown key. Check `pulumi config get aws:foo`.
```

---

The same config keys with an explicit provider succeed as expected.

```yaml
name: dev-yaml
runtime: yaml
config:
  aws:foo: bar
  aws:region: us-west-2

resources:
  aws:
    type: pulumi:providers:aws
    properties:
      region: us-west-2
    options:
      version: v6.1.0
  bucket:
    type: aws:s3:Bucket
    options:
      provider: ${aws}
```
