### ISSUE TITLE
Error: unable to find function "aws:getAmi" in resource provider "aws"

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-aws#3595]
### What happened?

Coming from https://github.com/pulumi/pulumi-yaml/blob/master/examples/webserver/Pulumi.yaml#L1 example

When using v6.25.0 this yields an error:

```
variables:
  ec2ami:
    fn::invoke:
      function: aws:getAmi
      arguments:
        filters:
          - name: name
            values: ["amzn2-ami-hvm-2.0.20231218.0-x86_64-ebs"]
        owners: ["137112412989"]
        mostRecent: true
      return: id
```

```
Error: unable to find function "aws:getAmi" in resource provider "aws"
```

Downgrading to aws-5.35.0 the error disappears. 

### Example

See above

### Output of `pulumi about`

```
CLI          
Version      3.99.0
Go Version   go1.21.5
Go Compiler  gc

Plugins
NAME  VERSION
yaml  unknown

Host     
OS       darwin
Version  14.2.1
Arch     x86_64

This project is written in yaml

Current Stack: anton-pulumi-corp/webserver/test-yaml-webserver

TYPE                                 URN
pulumi:pulumi:Stack                  urn:pulumi:test-yaml-webserver::webserver::pulumi:pulumi:Stack::webserver-test-yaml-webserver
pulumi:providers:aws                 urn:pulumi:test-yaml-webserver::webserver::pulumi:providers:aws::default
pulumi:providers:aws                 urn:pulumi:test-yaml-webserver::webserver::pulumi:providers:aws::UsEast2Provider
aws:ec2/securityGroup:SecurityGroup  urn:pulumi:test-yaml-webserver::webserver::aws:ec2/securityGroup:SecurityGroup::WebSecGrp
aws:s3/bucket:Bucket                 urn:pulumi:test-yaml-webserver::webserver::aws:s3/bucket:Bucket::MyBucket
aws:ec2/instance:Instance            urn:pulumi:test-yaml-webserver::webserver::aws:ec2/instance:Instance::WebServer


Found no pending operations associated with test-yaml-webserver

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/anton-pulumi-corp
User           anton-pulumi-corp
Organizations  anton-pulumi-corp, moolumi, pulumi
Token type     personal

No dependencies found

Pulumi locates its logs in /var/folders/gk/cchgxh512m72f_dmkcc3d09h0000gp/T/com.apple.shortcuts.mac-helper// by default

```

### Additional context

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
