### ISSUE TITLE
Creating an ACM Certificate times out without custom timeout

### ISSUE THREAD

**Issue by VenelinMartinov** [pulumi/pulumi-aws#3617]
### What happened?

The default timeout on ACM Certificate of 5m seems to be insufficient in most cases. This causes the creation to timeout before it manages to create the resource.

### Example

```yaml
name: acm
runtime: yaml
resources:
  certificate:
    type: aws:acm:Certificate
    properties:
      domainName: "example.com"
      validationMethod: "EMAIL"
      subjectAlternativeNames: ["www.example.com"]
    options:
      customTimeouts:
        create: "30m"
```

### Output of `pulumi about`

```
CLI          
Version      3.108.1
Go Version   go1.22.0
Go Compiler  gc

Plugins
NAME  VERSION
aws   unknown
yaml  unknown

Host     
OS       darwin
Version  14.1.1
Arch     arm64

This project is written in yaml

Current Stack: pulumi/acm/dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/venelin-pulumi-corp
User           venelin-pulumi-corp
Organizations  venelin-pulumi-corp, demo, pulumi
Token type     personal

No dependencies found

Pulumi locates its logs in /var/folders/82/nqnqw81s1h56l5nv940f9mq00000gn/T/ by default
```

AWS 6.25

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
