### ISSUE TITLE
Code property in lambda function creation does not support s3_bucket

### ISSUE THREAD

**Issue by raymzag** [pulumi/pulumi-aws#3632]
### What happened?

https://www.pulumi.com/registry/packages/aws/api-docs/lambda/function/#code_yaml

```
Path to the function's deployment package within the local filesystem. Exactly one of filename, image_uri, or s3_bucket must be specified.
```

### Example

```
  lambda_hello_world:
    type: aws:lambda:Function
    properties:
      code:
        s3Bucket: ${s3_bucket_lambda_code.bucket}
        s3Key: helloworld.zip
```

```
      code: Cannot assign '{s3Bucket: string, s3Key: string}' to 'archive'
```

### Output of `pulumi about`

```
CLI
Version      3.109.0
Go Version   go1.22.0
Go Compiler  gc

Plugins
NAME  VERSION
yaml  unknown

Host
OS       darwin
Version  14.3.1
Arch     arm64
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
