### ISSUE TITLE
Docs: Usage of defaultTags is not especially clear

### ISSUE THREAD

**Issue by jkodroff** [pulumi/pulumi-aws#4874]
When using `defaultTags` for the first time in the AWS Provider, I I found the docs on how to configure defaultTags to be a little confusing.  If you look at the screenshot below, it wasn't especially clear how to set this via `pulumi config set` or how to enter it in `Pulumi.stack.yaml` manually due to the use of the words "JSON block" and also how "Tags" appears below the option when "Tags" is really the value of the setting itself.

![image](https://user-images.githubusercontent.com/410614/145597011-dfcfbff3-03f8-4ddc-991f-a02f72042510.png)

Not entirely sure what tools we have at our disposal to improve.  Could be overriding the docs, or could be a change to how we generate the docs, or could be just adding an example that shows its usage.

FWIW, I ended up adding the config manually to `Pulumi.dev.yaml` like so:

```yaml
config:
  aws:defaultTags:
    tags:
      owner: platform-integrations
      repo: pulumi/github-issue-automation
```

**Comment by iwahbe** [comment]
I'm transferring this issue to pulumi-aws since the docs for this provider live in-repo.

**Comment by Mart-Bogdan** [comment]
For others who got here from Google as I did, here is a solution, that I've got after reading @ringods's response second time and after long time of struggle.

In main yaml file you should write:

```yaml
aws:defaultTags:
  value:
    tags:
      key: value
```

so adding `value:` node there.

For example:
```yaml
  aws:defaultTags:
    value: 
      tags:
        Pulumi: "true"
```
