### ISSUE TITLE
`cloudfront.Distribution` attempts to replace when an origin changes

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi-aws#5229]
### Describe what happened

When trying to move the Pulumi Registry from v5.42.0 to v6.69.0, Pulumi attempted to replace the distribution fronting the registry in Preview: https://app.pulumi.com/pulumi/registry/production/previews/bfda2b65-d7fb-4eb7-8bba-e74c51c63b98.

Tracking this down, we found a program that produces a radically different (and wrong) diff in v5.42.0 and v6.69.0.

### Sample program

To reproduce, run `pulumi up` on the example program.

Then force the bucket to replace:

```patch
  myBucket:
    type: aws:s3:Bucket
+   properties:
+     bucketPrefix: somePrefix
    options:
      version: v6.69.0
```

This will cause 2 replaces, when only the bucket should need to be replaced.

<details>
<summary> `$ pulumi preview --diff` </summary>

```
Previewing update (pulumi/dev)

View Live: https://app.pulumi.com/pulumi/dev-yaml/dev/previews/ccb8bce7-3b15-4c4a-a89b-2a3a61518979

warning: using pulumi-language-yaml from $PATH at /Users/ianwahbe/.pulumi/bin/pulumi-language-yaml
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:dev::dev-yaml::pulumi:pulumi:Stack::dev-yaml-dev]
    pulumi-internal-policies@v0.0.6 [advisory]  s3-bucket-replication-enabled  (aws:s3/bucket:Bucket: myBucket)Encourages use of cross-region replication for S3 buckets.
S3 buckets should have cross-region replication.
    +-aws:s3/bucket:Bucket: (replace)
        [id=mybucket-31f8cbf]
        [urn=urn:pulumi:dev::dev-yaml::aws:s3/bucket:Bucket::myBucket]
        [provider=urn:pulumi:dev::dev-yaml::pulumi:providers:aws::default_6_69_0::640c4d68-5bee-4c63-a50a-bfd55b463f2f]
      + bucketPrefix: "foo"
error: unable to replace resource "urn:pulumi:dev::dev-yaml::aws:cloudfront/distribution:Distribution::myDistribution"
as it is currently marked for protection. To unprotect the resource, remove the `protect` flag from the resource in your Pulumi program and run `pulumi up`
    +-aws:cloudfront/distribution:Distribution: (replace) 🔒
        [id=E2CMKKRQF1LB3L]
        [urn=urn:pulumi:dev::dev-yaml::aws:cloudfront/distribution:Distribution::myDistribution]
        [provider=urn:pulumi:dev::dev-yaml::pulumi:providers:aws::default_6_69_0::640c4d68-5bee-4c63-a50a-bfd55b463f2f]
      ~ origins: [
          ~ [0]: {
                  ~ connectionAttempts: 3 => 3
                  ~ connectionTimeout : 10 => 10
                  ~ domainName        : "mybucket-31f8cbf.s3.us-west-2.amazonaws.com" => output<string>
                  ~ originId          : "myBucketOrigin" => "myBucketOrigin"
                  ~ s3OriginConfig    : {
                      + __defaults          : []
                      ~ originAccessIdentity: "origin-access-identity/cloudfront/EA40M0HH9QM34" => "origin-access-identity/cloudfront/EA40M0HH9QM34"
                      ~ originAccessIdentity: "origin-access-identity/cloudfront/EA40M0HH9QM34" => "origin-access-identity/cloudfront/EA40M0HH9QM34"
                    }
                }
        ]
      + staging: false
error: preview failed
Resources:
    +-2 to replace
    2 unchanged

Policy Packs run:
    Name                      Version
    pulumi-internal-policies  0.0.6
```

</details>

<details>
<summary>
Example program
</summary>

```yaml
name: dev-yaml
runtime: yaml
resources:
  myBucket:
    type: aws:s3:Bucket
    options:
      version: v6.69.0
      
  myOriginAccessIdentity:
    type: aws:cloudfront:OriginAccessIdentity
    properties:
      comment: "OAI for my S3 bucket"
    options:
      version: v6.69.0

  myDistribution:
    type: aws:cloudfront:Distribution
    properties:
      restrictions:
        geoRestriction:
          restrictionType: none
      origins:
        - originId: myBucketOrigin
          domainName: ${myBucket.bucketRegionalDomainName}
          s3OriginConfig:
            originAccessIdentity: ${myOriginAccessIdentity.cloudfrontAccessIdentityPath}
      enabled: true
      defaultCacheBehavior:
        targetOriginId: myBucketOrigin
        viewerProtocolPolicy: allow-all
        allowedMethods:
          - GET
          - HEAD
        cachedMethods:
          - GET
          - HEAD
        forwardedValues:
          queryString: false
          cookies:
            forward: none
        minTtl: 0
        defaultTtl: 3600
        maxTtl: 86400
      priceClass: PriceClass_100
      viewerCertificate:
        cloudfrontDefaultCertificate: true
    options:
      version: v6.69.0
      protect: true
```

</details>

This behavior does not reproduce on pulumi-aws@v5.42.0.

### Output of `pulumi about`

```
CLI          
Version      3.151.0-dev.0
Go Version   go1.23.6
Go Compiler  gc

Plugins
KIND      NAME  VERSION
resource  aws   6.69.0
language  yaml  1.13.0

Host     
OS       darwin
Version  15.1.1
Arch     arm64

This project is written in yaml

Current Stack: pulumi/dev-yaml/dev

TYPE                                                      URN
pulumi:pulumi:Stack                                       urn:pulumi:dev::dev-yaml::pulumi:pulumi:Stack::dev-yaml-dev
pulumi:providers:aws                                      urn:pulumi:dev::dev-yaml::pulumi:providers:aws::default_6_69_0
aws:s3/bucket:Bucket                                      urn:pulumi:dev::dev-yaml::aws:s3/bucket:Bucket::myBucket
aws:cloudfront/originAccessIdentity:OriginAccessIdentity  urn:pulumi:dev::dev-yaml::aws:cloudfront/originAccessIdentity:OriginAccessIdentity::myOriginAccessIdentity
aws:cloudfront/distribution:Distribution                  urn:pulumi:dev::dev-yaml::aws:cloudfront/distribution:Distribution::myDistribution


Found no pending operations associated with pulumi/dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/ian-pulumi-corp
User           ian-pulumi-corp
Organizations  ian-pulumi-corp, pulumi
Token type     personal

Dependencies:
NAME  VERSION
aws   v6.69.0

Pulumi locates its logs in /var/folders/fg/_1q36r4j6yx0rwz2fbhjd5y40000gn/T/ by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
