### ISSUE TITLE
NodeGroup will always create a default launch template

### ISSUE THREAD

**Issue by syscl** [pulumi/pulumi-aws#5402]
### Describe what happened

Hi pulumi team/folks,

Hope all is well! I've noticed an issue with NodeGroup creation, that is no matter if I provide my own launch template or not, NodeGroup will always create its own launch template, here's the minimal reproduce code
```
import pulumi_aws as aws

cluster = aws.eks.Cluster("mycluster", ...)
lt = aws.ec2.LaunchTemplate("standard", block_device_mappings=[
            aws.ec2.LaunchTemplateBlockDeviceMappingArgs(
                device_name="/dev/xvda",
                ebs=aws.ec2.LaunchTemplateBlockDeviceMappingEbsArgs(
                    volume_size="40g",
                    encrypted=True,
                ),
            ),
        ],
...)
NodeGroup("nodegroup", cluster_name=cluster.name, 
  launch_template=aws.eks.NodeGroupLaunchTemplateArgs(
                    id=lt.id,
                    version=lt.latest_version
                ),
)

```
The problem is it always creates a default launch template, and attach the unencrypted disk to the instance, which is not allowed in our production environment.

Could you please take a look at how to disable the default launch template creation, or any code pointer we can take a look to fix it? Thanks

### Sample program

```
import pulumi_aws as aws

cluster = aws.eks.Cluster("mycluster", ...)
lt = aws.ec2.LaunchTemplate("standard", block_device_mappings=[
            aws.ec2.LaunchTemplateBlockDeviceMappingArgs(
                device_name="/dev/xvda",
                ebs=aws.ec2.LaunchTemplateBlockDeviceMappingEbsArgs(
                    volume_size="40g",
                    encrypted=True,
                ),
            ),
        ],
...)
NodeGroup("nodegroup", cluster_name=cluster.name, 
  launch_template=aws.eks.NodeGroupLaunchTemplateArgs(
                    id=lt.id,
                    version=lt.latest_version
                ),
)

```

### Output of `pulumi about`

no

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by VenelinMartinov** [comment]
Hey @syscl sorry you hit this. I was not able to reproduce the issue you described. Can you please check that you are using the newest pulumi-aws provider version? If yes, can you please give me some more detail on how to reproduce this?

Here is the code I tried:
<details>

```YAML
name: aws-eks-lt-repro
runtime: yaml
description: Reproduction for EKS NodeGroup launch template issue

resources:
  # VPC and Networking
  vpc:
    type: aws:ec2:Vpc
    properties:
      cidrBlock: "10.0.0.0/16"
      enableDnsHostnames: true
      enableDnsSupport: true
      tags:
        Name: eks-vpc
        "kubernetes.io/cluster/test-cluster": "shared"

  publicSubnet1:
    type: aws:ec2:Subnet
    properties:
      vpcId: ${vpc.id}
      cidrBlock: "10.0.1.0/24"
      availabilityZone: us-west-2a
      mapPublicIpOnLaunch: true
      tags:
        Name: eks-public-1
        "kubernetes.io/cluster/test-cluster": "shared"
        "kubernetes.io/role/elb": "1"

  publicSubnet2:
    type: aws:ec2:Subnet
    properties:
      vpcId: ${vpc.id}
      cidrBlock: "10.0.2.0/24"
      availabilityZone: us-west-2b
      mapPublicIpOnLaunch: true
      tags:
        Name: eks-public-2
        "kubernetes.io/cluster/test-cluster": "shared"
        "kubernetes.io/role/elb": "1"

  igw:
    type: aws:ec2:InternetGateway
    properties:
      vpcId: ${vpc.id}
      tags:
        Name: eks-igw

  routeTable:
    type: aws:ec2:RouteTable
    properties:
      vpcId: ${vpc.id}
      routes:
        - cidrBlock: "0.0.0.0/0"
          gatewayId: ${igw.id}
      tags:
        Name: eks-rt

  subnet1RouteTableAssoc:
    type: aws:ec2:RouteTableAssociation
    properties:
      subnetId: ${publicSubnet1.id}
      routeTableId: ${routeTable.id}

  subnet2RouteTableAssoc:
    type: aws:ec2:RouteTableAssociation
    properties:
      subnetId: ${publicSubnet2.id}
      routeTableId: ${routeTable.id}

  # IAM Roles
  eksRole:
    type: aws:iam:Role
    properties:
      name: eks-cluster-role
      assumeRolePolicy: |
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "Service": "eks.amazonaws.com"
              },
              "Action": "sts:AssumeRole"
            }
          ]
        }

  eksRolePolicyAttachment:
    type: aws:iam:RolePolicyAttachment
    properties:
      role: ${eksRole.name}
      policyArn: arn:aws:iam::aws:policy/AmazonEKSClusterPolicy

  nodeGroupRole:
    type: aws:iam:Role
    properties:
      name: eks-nodegroup-role
      assumeRolePolicy: |
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "Service": "ec2.amazonaws.com"
              },
              "Action": "sts:AssumeRole"
            }
          ]
        }

  nodeGroupRolePolicyAttachment1:
    type: aws:iam:RolePolicyAttachment
    properties:
      role: ${nodeGroupRole.name}
      policyArn: arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy

  nodeGroupRolePolicyAttachment2:
    type: aws:iam:RolePolicyAttachment
    properties:
      role: ${nodeGroupRole.name}
      policyArn: arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy

  nodeGroupRolePolicyAttachment3:
    type: aws:iam:RolePolicyAttachment
    properties:
      role: ${nodeGroupRole.name}
      policyArn: arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly

  # EKS Cluster
  cluster:
    type: aws:eks:Cluster
    properties:
      name: test-cluster
      roleArn: ${eksRole.arn}
      version: "1.27"
      vpcConfig:
        subnetIds: 
          - ${publicSubnet1.id}
          - ${publicSubnet2.id}
        endpointPrivateAccess: false
        endpointPublicAccess: true

  # Custom Launch Template
  customLaunchTemplate:
    type: aws:ec2:LaunchTemplate
    properties:
      name: custom-lt
      blockDeviceMappings:
        - deviceName: /dev/xvda
          ebs:
            volumeSize: 40
            volumeType: gp3
            encrypted: true
      vpcSecurityGroupIds:
        - ${cluster.vpcConfig.clusterSecurityGroupId}
      tags:
        Name: custom-lt

  # EKS Node Group
  nodeGroup:
    type: aws:eks:NodeGroup
    properties:
      clusterName: ${cluster.name}
      nodeGroupName: test-nodegroup
      nodeRoleArn: ${nodeGroupRole.arn}
      subnetIds:
        - ${publicSubnet1.id}
        - ${publicSubnet2.id}
      instanceTypes: ["t3.medium"]
      launchTemplate:
        id: ${customLaunchTemplate.id}
        version: ${customLaunchTemplate.latestVersion}
      scalingConfig:
        desiredSize: 1
        maxSize: 2
        minSize: 1 
```

</details>

I checked the attached launch templates with

```
aws eks describe-nodegroup --cluster-name test-cluster --nodegroup-name test-nodegroup
```

and verified all the attached volumes are encrypted.
